import { describe, expect, it } from "vitest";
import { claudeCodeDisplayHints, claudeSlashCommandName, isTagOnlyMessage } from "./systemMessage";

describe("isTagOnlyMessage", () => {
  describe("folds (tags only, no top-level body text)", () => {
    it("a single tag wrapping the whole message", () => {
      expect(
        isTagOnlyMessage(
          "<local-command-caveat>Caveat: The messages below were generated by the user.</local-command-caveat>",
        ),
      ).toBe(true);
    });

    it("multiple system tags separated by whitespace", () => {
      expect(
        isTagOnlyMessage(
          "<command-name>/clear</command-name> <command-message>clear</command-message> <command-args></command-args>",
        ),
      ).toBe(true);
    });

    it("an empty element tag", () => {
      expect(isTagOnlyMessage("<command-args></command-args>")).toBe(true);
    });

    it("surrounding whitespace and newlines only", () => {
      expect(isTagOnlyMessage("\n  <a>x</a>\n<b>y</b>  ")).toBe(true);
    });

    it("nested tags (only the outer is top-level)", () => {
      expect(isTagOnlyMessage("<outer><inner>text</inner></outer>")).toBe(true);
    });

    it("a self-closing tag", () => {
      expect(isTagOnlyMessage("<br/>")).toBe(true);
    });

    it("inequality characters inside tag content (depth > 0, ignored)", () => {
      expect(isTagOnlyMessage("<expr>a < b > c</expr>")).toBe(true);
    });

    it("an attributed tag", () => {
      expect(isTagOnlyMessage('<note level="info">x</note>')).toBe(true);
    });
  });

  describe("does not fold (real body text or no tags)", () => {
    it("plain text", () => {
      expect(isTagOnlyMessage("これは普通のテキストです")).toBe(false);
    });

    it("body text after a tag", () => {
      expect(isTagOnlyMessage("<command>ls</command> してください")).toBe(false);
    });

    it("body text before a tag", () => {
      expect(isTagOnlyMessage("次のコードを実行: <command>ls</command>")).toBe(false);
    });

    it("an empty string", () => {
      expect(isTagOnlyMessage("")).toBe(false);
    });

    it("whitespace only", () => {
      expect(isTagOnlyMessage("   \n ")).toBe(false);
    });

    it("a top-level inequality expression", () => {
      expect(isTagOnlyMessage("5 < 10 は真")).toBe(false);
    });

    it("a text prefix glued to a tag", () => {
      expect(isTagOnlyMessage("prefix<tag>x</tag>")).toBe(false);
    });

    it("an unclosed tag (broken input, fail safe)", () => {
      expect(isTagOnlyMessage("<command-name>/clear")).toBe(false);
    });

    it("entities only, no tags", () => {
      expect(isTagOnlyMessage("&amp; &lt;")).toBe(false);
    });
  });
});

describe("claudeCodeDisplayHints", () => {
  it("folds Claude Code external meta prompts using metadata only", () => {
    expect(
      claudeCodeDisplayHints(
        "arbitrary prompt text",
        JSON.stringify({
          source: "claude_code",
          kind: "user",
          entry_type: "user",
          block_type: "text",
          claude_code: { is_meta: true, user_type: "external" },
        }),
      ),
    ).toEqual({ collapsed: true, commandName: null });
  });

  it("does not fold legacy Claude Code prompt-shaped content without claude_code metadata", () => {
    expect(
      claudeCodeDisplayHints(
        "<!--\nname: 'Agent Prompt: /review slash command'\n-->\nPrompt body",
        JSON.stringify({ source: "claude_code", kind: "user", entry_type: "user" }),
      ),
    ).toEqual({ collapsed: false, commandName: null });
  });

  it("extracts a slash command name only for a metadata-confirmed invocation", () => {
    expect(
      claudeCodeDisplayHints(
        "<command-message>review</command-message>\n<command-name>/review</command-name>",
        JSON.stringify({
          source: "claude_code",
          kind: "user",
          entry_type: "user",
          block_type: "text",
          claude_code: { user_type: "external" },
        }),
      ),
    ).toEqual({ collapsed: false, commandName: "/review" });
  });

  it("does not extract slash command tags without the Claude Code metadata contract", () => {
    expect(
      claudeCodeDisplayHints(
        "<command-message>review</command-message>\n<command-name>/review</command-name>",
        null,
      ),
    ).toEqual({ collapsed: false, commandName: null });
  });

  it("folds Claude Code system scaffolding by metadata", () => {
    expect(
      claudeCodeDisplayHints(
        "task reminder",
        JSON.stringify({
          source: "claude_code",
          kind: "attachment",
          entry_type: "attachment",
          subtype: "task_reminder",
          claude_code: { entrypoint: "cli" },
        }),
      ),
    ).toEqual({ collapsed: true, commandName: null });
  });

  it("treats broken metadata as normal content", () => {
    expect(claudeCodeDisplayHints("x", "{bad json")).toEqual({
      collapsed: false,
      commandName: null,
    });
  });
});

describe("claudeSlashCommandName", () => {
  it("extracts command-name from tag-only command content", () => {
    expect(
      claudeSlashCommandName(
        "<command-message>review</command-message>\n<command-name>/review</command-name>",
      ),
    ).toBe("/review");
  });

  it("falls back to command-message", () => {
    expect(claudeSlashCommandName("<command-message>review</command-message>")).toBe("/review");
  });

  it("does not extract from mixed body text", () => {
    expect(claudeSlashCommandName("<command-name>/review</command-name> を実行")).toBeNull();
  });
});
