//! Render the `auto-embedding-workers.yaml` so the embedding-runner
//! settings (model id, optional tokenizer id, dtype, device, max
//! sequence length) reflect the user's [`EmbeddingRuntime`].
//!
//! The committed `workers/workflows/auto-embedding-workers.yaml` is the
//! reference for everything except the runner's `settings:` block, which
//! is rewritten here. The rest (channel, retry policy, the
//! `memories-upsert-embedding` GRPC worker, the WORKFLOW dispatcher) is
//! copied through unchanged.
//!
//! Why a renderer and not pure `expand_env`: the `tokenizer_model_id`
//! line must be **dropped entirely** when the runtime has no tokenizer
//! override (so the embedding runner falls back to its model-id-driven
//! default). YAML `expand_env` cannot drop a key — it can only substitute
//! a value — so the file is staged into `<data>/workers/staged/` at
//! sidecar startup with the line either present or absent, and the
//! sidecar's `MEMORY_WORKERS_YAML` env is pointed at the staged copy.

use std::path::{Path, PathBuf};

use crate::data::DataPaths;
use crate::error::{AppError, AppResult};

use super::embedding_settings::EmbeddingRuntime;

/// File name used for the staged YAML. Matches the committed bundle's
/// name so `MEMORY_WORKERS_YAML` semantics are identical on both paths.
pub const STAGED_AUTO_EMBEDDING_WORKERS_YAML: &str = "auto-embedding-workers.yaml";

/// 10 MiB upper bound on a single image payload. Kept regardless of
/// multimodality so a text-only swap doesn't need a YAML restage when
/// the user later switches back to a multimodal preset. The runner
/// silently ignores this when the model can't embed images.
const EMBEDDING_IMAGE_SIZE_LIMIT_BYTES: u32 = 10 * 1024 * 1024;

/// Render the YAML body for `auto-embedding-workers.yaml` against
/// `runtime`. The output parses as a valid YAML document.
pub fn render_auto_embedding_workers_yaml(runtime: &EmbeddingRuntime) -> String {
    let mut settings = format!("      model_id: \"{}\"\n", yaml_escape(&runtime.model_id));
    if let Some(tok) = runtime.tokenizer_id.as_deref() {
        settings.push_str(&format!(
            "      tokenizer_model_id: \"{}\"\n",
            yaml_escape(tok)
        ));
    }
    settings.push_str(&format!("      device: {}\n", embedding_device()));
    settings.push_str(&format!("      dtype: {}\n", yaml_escape(&runtime.dtype)));
    settings.push_str(&format!(
        "      max_sequence_length: {}\n",
        runtime.max_sequence_length
    ));
    settings.push_str(&format!(
        "      image_size_limit_bytes: {EMBEDDING_IMAGE_SIZE_LIMIT_BYTES}\n"
    ));
    settings.push_str(&format!(
        "      chunking_config:\n        max_chunk_tokens: {}\n        min_chunk_tokens: 0\n",
        runtime.max_sequence_length
    ));

    format!(
        r#"# Auto-generated by lookback-tauri (commands::embedding_workers_yaml).
# DO NOT EDIT — re-render by saving Embedding settings in the Lookback app.
# Mirrors workers/workflows/auto-embedding-workers.yaml; only the
# memories-mm-embedding settings block changes per-user.

defaults:
  response_type: DIRECT
  store_failure: true
  broadcast_results: false
  retry_policy:
    type: EXPONENTIAL
    interval: 800
    max_interval: 60000
    max_retry: 0
    basis: 2.0

workers:
  - name: memories-mm-embedding
    runner: MultimodalEmbeddingRunner
    use_static: true
    channel: embedding
    settings:
{settings}
  - name: memories-upsert-embedding
    runner: GRPC
    settings:
      host: "%{{MEMORY_GRPC_HOST}}"
      port: "%{{MEMORY_GRPC_PORT}}"
      use_reflection: true
      method: llm_memory.service.MemoryVectorService/BatchUpsertEmbeddings
      as_json: true

  - name: memories-auto-embedding
    runner: WORKFLOW
    response_type: NO_RESULT
    channel: embedding_workflow
    settings:
      workflow_data:
        $file: auto-embedding.yaml
"#
    )
}

/// Minimal escaper for the YAML double-quoted scalar — flips backslashes
/// and embedded double quotes. The values that flow through here are
/// HuggingFace repo ids and enum names, so this is sufficient.
fn yaml_escape(s: &str) -> String {
    s.replace('\\', r"\\").replace('"', r#"\""#)
}

// The mm-embedding-runner crate is built with one backend (`metal`, `cuda`, or
// CPU-only) and refuses to register under any other `device` value
// (`UnsupportedDevice`), so the legal value is fixed by the staged plugin
// binary, not user-selectable.
fn embedding_device() -> &'static str {
    embedding_device_for(std::env::consts::OS, option_env!("LOOKBACK_EMBEDDING_GPU"))
}

fn embedding_device_for(target_os: &str, packaged_gpu: Option<&str>) -> &'static str {
    match packaged_gpu
        .map(|s| s.trim().to_ascii_lowercase())
        .as_deref()
    {
        Some("metal") => "Metal",
        Some("cuda") => "CUDA",
        Some("cpu") => "CPU",
        _ if target_os == "macos" => "Metal",
        _ => "CUDA",
    }
}

/// Write the rendered YAML into the staged workers dir and return the
/// path. The companion `auto-embedding.yaml` is copied alongside so
/// `$file: auto-embedding.yaml` resolves against the same directory.
///
/// Returns `Err` when the companion YAML cannot be located in the bundle:
/// the rendered staged file references `$file: auto-embedding.yaml`, so
/// writing it without the sibling would make `MEMORY_WORKERS_YAML` point
/// at a file whose worker registration is doomed to fail at startup.
/// The caller falls back to the committed bundle YAML in that case
/// (which DOES sit next to its `auto-embedding.yaml`) — at the cost of
/// the user's custom embedding settings not flowing through, but with
/// the upside of a sidecar that actually starts.
pub fn stage_auto_embedding_workers_yaml(
    runtime: &EmbeddingRuntime,
    data: &DataPaths,
    bundled_workflows_dir: Option<&Path>,
) -> AppResult<PathBuf> {
    let bundle = bundled_workflows_dir.ok_or_else(|| {
        AppError::Config(
            "stage_auto_embedding_workers_yaml: no bundled workflows dir; cannot resolve companion `auto-embedding.yaml`"
                .to_string(),
        )
    })?;
    let companion_src = bundle.join("auto-embedding.yaml");
    if !companion_src.exists() {
        return Err(AppError::Config(format!(
            "stage_auto_embedding_workers_yaml: companion `auto-embedding.yaml` not found at {}",
            companion_src.display()
        )));
    }

    let staged_dir = data.staged_workers_dir();
    std::fs::create_dir_all(&staged_dir).map_err(|e| {
        AppError::Config(format!(
            "create staged workers dir {}: {e}",
            staged_dir.display()
        ))
    })?;

    // Stage the companion FIRST so a partial failure (companion copy
    // erroring after the worker YAML is written) cannot leave behind a
    // stale `auto-embedding-workers.yaml` pointing at a missing `$file`.
    // `std::fs::copy` is idempotent on this tiny YAML; not worth a
    // mtime-skip helper.
    let companion_dst = staged_dir.join("auto-embedding.yaml");
    std::fs::copy(&companion_src, &companion_dst).map_err(|e| {
        AppError::Config(format!(
            "copy auto-embedding.yaml {} → {}: {e}",
            companion_src.display(),
            companion_dst.display()
        ))
    })?;

    let target = staged_dir.join(STAGED_AUTO_EMBEDDING_WORKERS_YAML);
    let body = render_auto_embedding_workers_yaml(runtime);
    std::fs::write(&target, body)
        .map_err(|e| AppError::Config(format!("write staged yaml {}: {e}", target.display())))?;
    Ok(target)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::commands::embedding_presets;
    use crate::commands::embedding_settings::resolve_embedding_runtime;

    fn default_runtime() -> EmbeddingRuntime {
        resolve_embedding_runtime(&Default::default())
    }

    #[test]
    fn render_default_preset_omits_tokenizer_line() {
        // Every shipped preset has `tokenizer_hf_repo: None`. The default
        // runtime must therefore render WITHOUT a `tokenizer_model_id:`
        // line — present-but-empty would crash the runner.
        let yaml = render_auto_embedding_workers_yaml(&default_runtime());
        assert!(!yaml.contains("tokenizer_model_id"));
    }

    #[test]
    fn render_default_preset_uses_default_model_id() {
        let yaml = render_auto_embedding_workers_yaml(&default_runtime());
        let preset = embedding_presets::default_preset();
        assert!(
            yaml.contains(&format!("model_id: \"{}\"", preset.hf_repo)),
            "rendered YAML does not contain default model_id: {yaml}"
        );
    }

    #[test]
    fn render_includes_tokenizer_line_when_runtime_has_one() {
        let runtime = EmbeddingRuntime {
            model_id: "intfloat/multilingual-e5-base".into(),
            tokenizer_id: Some("intfloat/multilingual-e5-large".into()),
            vector_size: 768,
            dtype: "BF16".into(),
            max_sequence_length: 512,
            is_multimodal: false,
        };
        let yaml = render_auto_embedding_workers_yaml(&runtime);
        assert!(yaml.contains("tokenizer_model_id: \"intfloat/multilingual-e5-large\""));
    }

    #[test]
    fn render_propagates_dtype_and_platform_device() {
        let runtime = EmbeddingRuntime {
            model_id: "org/name".into(),
            tokenizer_id: None,
            vector_size: 1024,
            dtype: "BF16".into(),
            max_sequence_length: 256,
            is_multimodal: false,
        };
        let yaml = render_auto_embedding_workers_yaml(&runtime);
        assert!(yaml.contains("dtype: BF16"));
        assert!(yaml.contains(&format!("device: {}", embedding_device())));
        assert!(yaml.contains("max_sequence_length: 256"));
    }

    #[test]
    fn embedding_device_tracks_packaged_gpu_backend() {
        assert_eq!(embedding_device_for("macos", Some("metal")), "Metal");
        assert_eq!(embedding_device_for("linux", Some("cuda")), "CUDA");
        assert_eq!(embedding_device_for("linux", Some("cpu")), "CPU");
    }

    #[test]
    fn rendered_yaml_parses_as_valid_yaml() {
        // A round-trip through serde_yaml catches structural issues
        // (wrong indent, missing colons) that string assertions can't.
        let runtime = default_runtime();
        let yaml = render_auto_embedding_workers_yaml(&runtime);
        let parsed: serde_yaml::Value = serde_yaml::from_str(&yaml).unwrap_or_else(|e| {
            panic!("rendered YAML does not parse: {e}\n---\n{yaml}\n---");
        });
        // Spot-check the structure: workers[0].name = memories-mm-embedding.
        let workers = parsed.get("workers").and_then(|v| v.as_sequence()).unwrap();
        let mm = workers
            .iter()
            .find(|w| w.get("name").and_then(|n| n.as_str()) == Some("memories-mm-embedding"))
            .expect("memories-mm-embedding worker present");
        let model = mm
            .get("settings")
            .and_then(|s| s.get("model_id"))
            .and_then(|s| s.as_str())
            .unwrap();
        assert_eq!(model, runtime.model_id);
    }

    #[test]
    fn yaml_escape_handles_double_quote_in_repo() {
        // Defensive: HF repo ids never contain `"`, but if a custom
        // entry sneaks one in, the escaper must keep the YAML parseable.
        let runtime = EmbeddingRuntime {
            model_id: "org/with\"quote".into(),
            tokenizer_id: None,
            vector_size: 768,
            dtype: "F16".into(),
            max_sequence_length: 512,
            is_multimodal: false,
        };
        let yaml = render_auto_embedding_workers_yaml(&runtime);
        let parsed: serde_yaml::Value = serde_yaml::from_str(&yaml).unwrap();
        let workers = parsed.get("workers").and_then(|v| v.as_sequence()).unwrap();
        let model = workers
            .iter()
            .find(|w| w.get("name").and_then(|n| n.as_str()) == Some("memories-mm-embedding"))
            .and_then(|w| w.get("settings").and_then(|s| s.get("model_id")))
            .and_then(|s| s.as_str())
            .unwrap();
        assert_eq!(model, "org/with\"quote");
    }

    #[test]
    fn stage_writes_to_staged_workers_dir() {
        let tmp = tempfile::tempdir().unwrap();
        let data = DataPaths::with_root(tmp.path().to_path_buf());
        let bundle = tmp.path().join("bundle");
        std::fs::create_dir_all(&bundle).unwrap();
        std::fs::write(bundle.join("auto-embedding.yaml"), b"do: []\n").unwrap();
        let runtime = default_runtime();
        let path = stage_auto_embedding_workers_yaml(&runtime, &data, Some(&bundle)).unwrap();
        assert_eq!(
            path,
            data.staged_workers_dir()
                .join(STAGED_AUTO_EMBEDDING_WORKERS_YAML)
        );
        assert!(path.exists());
        let body = std::fs::read_to_string(&path).unwrap();
        assert!(body.contains("memories-mm-embedding"));
    }

    #[test]
    fn stage_copies_auto_embedding_yaml_alongside() {
        // The WORKFLOW worker uses `$file: auto-embedding.yaml` so the
        // sibling file must be staged too — else jobworkerp's loader
        // fails to register the workflow worker at startup.
        let tmp = tempfile::tempdir().unwrap();
        let data = DataPaths::with_root(tmp.path().to_path_buf());
        let bundle = tmp.path().join("bundle");
        std::fs::create_dir_all(&bundle).unwrap();
        std::fs::write(bundle.join("auto-embedding.yaml"), b"do: []\n").unwrap();

        let runtime = default_runtime();
        stage_auto_embedding_workers_yaml(&runtime, &data, Some(&bundle)).unwrap();

        let staged_sibling = data.staged_workers_dir().join("auto-embedding.yaml");
        assert!(staged_sibling.exists(), "sibling YAML not staged");
        assert_eq!(
            std::fs::read_to_string(&staged_sibling).unwrap(),
            "do: []\n"
        );
    }

    #[test]
    fn stage_errors_when_bundle_dir_missing() {
        // Regression: writing a staged YAML whose `$file: auto-embedding.yaml`
        // cannot be resolved would point `MEMORY_WORKERS_YAML` at a file the
        // worker loader cannot register. Refuse to stage in that case so the
        // caller falls back to the committed bundle path.
        let tmp = tempfile::tempdir().unwrap();
        let data = DataPaths::with_root(tmp.path().to_path_buf());
        let err = stage_auto_embedding_workers_yaml(&default_runtime(), &data, None).unwrap_err();
        assert!(
            matches!(err, crate::error::AppError::Config(_)),
            "expected AppError::Config, got {err:?}"
        );
        let staged_target = data
            .staged_workers_dir()
            .join(STAGED_AUTO_EMBEDDING_WORKERS_YAML);
        assert!(
            !staged_target.exists(),
            "staged worker YAML must NOT be written when companion is missing"
        );
    }

    #[test]
    fn stage_errors_when_companion_missing_in_bundle() {
        // Same protection as above, but for the case where the bundle dir
        // exists yet `auto-embedding.yaml` is absent (broken install / dev
        // setup that only copied the worker YAML).
        let tmp = tempfile::tempdir().unwrap();
        let data = DataPaths::with_root(tmp.path().to_path_buf());
        let bundle = tmp.path().join("bundle");
        std::fs::create_dir_all(&bundle).unwrap();
        let err = stage_auto_embedding_workers_yaml(&default_runtime(), &data, Some(&bundle))
            .unwrap_err();
        assert!(
            matches!(err, crate::error::AppError::Config(_)),
            "expected AppError::Config, got {err:?}"
        );
        let staged_target = data
            .staged_workers_dir()
            .join(STAGED_AUTO_EMBEDDING_WORKERS_YAML);
        assert!(
            !staged_target.exists(),
            "staged worker YAML must NOT be written when companion is missing"
        );
    }
}
